'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class LOG_CLIENT
    Public Property ID_LOG_CLIENT As Integer
    Public Property ID_CLIENT As Integer
    Public Property THE_USER As String
    Public Property CRUD_ACTION As String
    Public Property DATE_ACTION As Date

    Public Overridable Property THE_CLIENT As THE_CLIENT
    Public Overridable Property THE_USERS As THE_USERS

End Class
