'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class THE_USERS
    Public Property THE_USER As String
    Public Property THE_PSW As String
    Public Property NAME As String
    Public Property LASTNAME As String

    Public Overridable Property LOG_CLIENT As ICollection(Of LOG_CLIENT) = New HashSet(Of LOG_CLIENT)
    Public Overridable Property THE_CLIENT As ICollection(Of THE_CLIENT) = New HashSet(Of THE_CLIENT)

End Class
