'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class THE_CLIENT
    Public Property ID_CLIENT As Integer
    Public Property NAME As String
    Public Property LASTNAME As String
    Public Property CRUD_ACTION As String
    Public Property USR_CRUD_ACTION As String
    Public Property DATE_ACTION As Date

    Public Overridable Property LOG_CLIENT As ICollection(Of LOG_CLIENT) = New HashSet(Of LOG_CLIENT)
    Public Overridable Property THE_USERS As THE_USERS

End Class
